if GetLocale() ~= "ptBR" then return end
GNF_EDIT_FILTER_RANKS	= "Ignorar"
GNF_FILTER_RANKS		= "Classes"
GNF_IGNORED_RANKS       = "Clique para ignorar"
GNF_MIN_ITEM_LEVEL      = "Min item Level"
GNF_IGNORED_WORDS       = "Palavras Ignoradas"
GNF_IGNORED_WORD_INFO   = "Separar palavras com uma vírgula \",\""
GNF_ENFORCED_WORDS      = "Palavras forçadas"
GNF_GUILD_MEMBER        = "Membro da Guild"
